### PR TITLE
Implement allocate API endpoint

### PR DESCRIPTION
**Pull request by colinbruce**
+ add endpoint to API root
+ create tests for the handling of the POST
+ implement the endpoint

### CODE REVIEW

**Comment by slorek** [comment]
🤔 is not /claims/allocate-to-caseworker ? 👹

**Comment by colinbruce** [comment]
Who else would we allocate to @slorek ?
**Update:** I see what you mean now
But we are `POST`ing claim ids to `api/case_workers/allocate`
Why not `api/case_workers/allocate-claims`?

**Comment by slorek** [comment]
Just my pedantic side - the action of allocating is a modification against a claim resource, you're not modifying the case worker. And it should be a PUT/PATCH rather than POST ;) The allocate-to-caseworker makes it more obvious what it means, as otherwise you assume a bit of domain knowledge.

That said, you could do /case_worker/:id/allocate-claims. That would make sense. Apart from the mix of underscores and hyphens ;)

**Comment by slorek** [comment]
Another option - assuming de-allocation and listing allocations is useful, might be to expose `allocations` as a resource, allowing CRUD actions against that. E.g. POST to `/allocations` creates a new allocation, DELETE `/allocations/:id` de-allocates.

**Pull request closed without merging**
