### PR TITLE
Remove link from the legend

### PR DESCRIPTION
**Pull request by naseberry**
#### What
Remove the 'Remove' link from the `<legend>` so the hypertext does not interfere with the grouping of the inputs

#### Ticket
[Link within Legend](https://dsdmoj.atlassian.net/browse/CBO-1503)

#### Why
When navigating through the forms out of context, form elements that contain the word 'Remove' is confusing as users are entering information.

### CODE REVIEW

**Review by jsugarman — COMMENTED** [review]
Hard to see what has actually changed because it is just one commit. I assume most changes are just indentations in the views.

**Review by jsugarman — COMMENTED** [review]
has anyone, other than yourself, manually reviewed this on an environment?

**Comment by naseberry** [comment]
> Hard to see what has actually changed because it is just one commit. I assume most changes are just indentations in the views.

The cocoon remove link association was within the legend tag, when navigating through the forms out of context, form elements that contain the word 'Remove' is confusing as users are entering information.

This commit, moves the 'remove' link outside the `<legeng>` tag.

There were long standing markup errors where inputs were not properly grouped within the relevant `<fieldset>`, therefore the indentation changes.

remove-link

**Review by jsugarman — APPROVED** [review]
👍 reviewed and regression tested by designer so good to go.

**Pull request merged**
