### PR TITLE
Bump rails from 6.1.3.2 to 6.1.4.1

### PR DESCRIPTION
**Pull request by jsugarman**
Bumps [rails](https://github.com/rails/rails) from 6.1.3.2 to 6.1.4.1.
- [Release notes](https://github.com/rails/rails/releases)
- [Commits](https://github.com/rails/rails/compare/v6.1.3.2...v6.1.4.1)

---
updated-dependencies:
- dependency-name: rails
  dependency-type: direct:production
  update-type: version-update:semver-patch
...

### CODE REVIEW

**Comment by jsugarman** [comment]
@jrmhaig @naseberry This is a cherry pick of the rails dependabot branch that was reverted. For reimplementation. 

If you take a look at my `js/broken` it contains this change plus the webpack-dev-server. I am not sure if it is the combination of the two that broke the app

**Comment by jsugarman** [comment]
oops, closed with comment accidentally. reopened

**Comment by naseberry** [comment]
@jsugarman @jrmhaig it is the webpack-dev-server PR that broke it, specifically one incorrect dependency change I had introduced.

**Review by jrmhaig — APPROVED** [review]
I have got this branch running locally without problems so I am confident we can bump Rails safely.

**Comment by jsugarman** [comment]
sanity tested on staging and all fine. merging...

**Pull request merged**
