### PR TITLE
Remove dropzone gem

### PR DESCRIPTION
**Pull request by naseberry**
#### What
Removal of the Dropzonejs gem

#### Why
Dropzonejs is now loaded via yarn

### CODE REVIEW

**Comment by jsugarman** [comment]
have you tested this on an actual environment @naseberry  - the reason being i don't believe the testing round this area is not great and there was some custom js that may or may not be being used

**Comment by naseberry** [comment]
> have you tested this on an actual environment @naseberry - the reason being i don't believe the testing round this area is not great and there was some custom js that may or may not be being used

Only tested locally, I shall test this in an environment

**Comment by naseberry** [comment]
@jsugarman I have sanity checked user journeys for agfs, lgfs and caseworker on staging.
All references to 'dropzone' are in reference to the multiple file upload component, this dependency is now loaded via yarn.

**Comment by jsugarman** [comment]
> @jsugarman I have sanity checked user journeys for agfs, lgfs and caseworker on staging.
> All references to 'dropzone' are in reference to the multiple file upload component, this dependency is now loaded via yarn.

great, approving

**Review by jsugarman — APPROVED** [review]
👍

**Pull request merged**
