### PR TITLE
[CFP-331] Removal of dead codes

### PR DESCRIPTION
**Pull request by imtiazAhmd**
#### What
During the work commenced on the Final Table Migration [CFP-235](https://dsdmoj.atlassian.net/browse/CFP-235), we have identified some dead codes in our CCCD codebase. Dead code adds unnecessary complexity to the codebase. It makes the codebase more difficult to understand and maintain in the long run. It impacts performance and security.

#### Ticket
[CFP-331 Remove all identified potential dead codes](https://dsdmoj.atlassian.net/browse/CFP-331)

--------
#### Documentation (Decision Log)
https://dsdmoj.atlassian.net/l/c/uYjaPHiA

--------

#### TODO
- [x] app/views/external_users/claims/supporting_documents/_summary.html.haml
- [x] app/views/external_users/claims/supporting_evidence_checklist/_summary.html.haml
- [x] app/views/case_workers/admin/case_workers/_claim.html.haml
- [x] app/views/shared/_summary.html.haml
--------
 **Identify the use-cases of `user_message_statuses` and if found not in use, remove references from these files:** 
   - [x] app/controllers/user_message_statuses_controller.rb
   - [x] app/views/user_message_statuses/index.html.haml
   - [x] app/views/user_message_statuses/update.js.erb
   - [x] config/routes.rb
   - [x] spec/controllers/user_message_statuses_controller_spec.rb
--------
**Sanity check on `staging`
   - [x] as `advocate / advocateAdmin`
   - [x] as `litigator / litigatorAdmin`
   - [x] as `caseworker / caseworkerAdmin`

### CODE REVIEW

**Comment by naseberry** [comment]
Good stuff @imtiazAhmd 
Have you checked for related dead code in our stylesheet, javascript and translation files?

**Comment by imtiazAhmd** [comment]
> 

Yes @naseberry, I did to the best of my knowledge. I just did a double check. Hope I didn't miss anything.

**Review by naseberry — APPROVED** [review]
I've sanity checked the lgfs journey, looks good.

Nit: As `t('.caption')` in both `app/views/external_users/claims/supporting_documents/_summary.html.haml` and `app/views/external_users/claims/supporting_evidence_checklist/_summary.html.haml` are now redundant, removing them from the translation file won't make a dent in the clean-up process, but, every little helps.

**Comment by imtiazAhmd** [comment]
> I've sanity checked the lgfs journey, looks good.
> 
> Nit: As `t('.caption')` in both `app/views/external_users/claims/supporting_documents/_summary.html.haml` and `app/views/external_users/claims/supporting_evidence_checklist/_summary.html.haml` are now redundant, removing them from the translation file won't make a dent in the clean-up process, but, every little helps.

Done ! removed from the translation 👍🏼

**Review by jrmhaig — APPROVED** [review]

**Review by jsugarman — APPROVED** [review]

**Pull request merged**
