### PR TITLE
Upgrade to Rails 5.2

### PR DESCRIPTION
**Pull request by lostie**
#### What

🚧 **DO NOT MERGE**

#### Ticket

[board ticket description](link)

#### How

* [Rails upgrade from 5.0 to 5.1](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-0-to-rails-5-1)
* [Rails upgrade from 5.1 to 5.2](http://edgeguides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-1-to-rails-5-2)

### CODE REVIEW

**Comment by lostie** [comment]
I still need to deploy it somewhere and get someone to do some manual tests to check if there's nothing unexpected still failing but I've finally managed to go through all the deprecations and failing specs and got it 💚 .

**Review by colinbruce — APPROVED** [review]
Looks good :+1:

**Comment by lostie** [comment]
Currently 🚫 due to some (possibly) Unicorn related issues. Investigating...

**Comment by lostie** [comment]
Update: Still didn't have the time to investigate further into the issue :S

**Pull request closed without merging**
