### PR TITLE
[CFP-154] Replace app typography with that of the GOV.UK Design System [3 of 4]

### PR DESCRIPTION
**Pull request by naseberry**
#### What

Replace app body typography with that of the GOV.UK Design System

#### Ticket

[Replace stylesheet typography](https://dsdmoj.atlassian.net/browse/CFP-153)

#### Why

To continue the migration away from the deprecated GOV.UK Elements to GOV.UK Frontend (GOV.UK Design System)

#### How

| GOV.UK Elements | GOV.UK Frontend |
| --- | ----------- |
| `lede` | `govuk-body-l` |
| `<p>`<br> `body-text` | `govuk-body` |
| `font-xsmall` | `govuk-body-s` |
| `<hr>` | `govuk-section-break`<br> `govuk-section-break--visible`<br> `govuk-section-break--xl`<br> `govuk-section-break--l`<br> `govuk-section-break--m` |

### CODE REVIEW

**Comment by naseberry** [comment]
This replaces the deprecated body classes with the new ones.

see: https://design-system.service.gov.uk/get-started/updating-your-code/

**Review by jsugarman — APPROVED** [review]
Be good to have screenshot examples of what differences this makes, if any, and what we should therefore be looking out for during a review.

otherwise I am inclined to just 👍

**Comment by jrmhaig** [comment]
Some spacing has been lost on the api release notes page (/api/release_notes). Was this intended?

**Before:**

Screenshot 2021-07-02 at 11 25 04

**After:**

Screenshot 2021-07-02 at 11 25 17

**Comment by naseberry** [comment]
> Be good to have screenshot examples of what differences this makes, if any, and what we should therefore be looking out for during a review.
> 
> otherwise I am inclined to just 👍

The new classes will bring change to font family and color and size, margins and paddings.
Too many property changes to list them all.

**Comment by naseberry** [comment]
> Some spacing has been lost on the api release notes page (/api/release_notes). Was this intended?

We can increase the section size to `.govuk-section-break--l`

**Pull request merged**
