### PR TITLE
Bump codeclimates rubocop from 0-83 to 0-92

### PR DESCRIPTION
**Pull request by jsugarman**
This should have been part of the rubocop gem bump to
version 0.93.1.

#### What
Bump codeclimates rubocop from 0-83 to 0-92

The latest available version for codeclimate at time of
writing is 0-92

see https://github.com/codeclimate/codeclimate-rubocop/branches/all?utf8=%E2%9C%93&query=channel%2Frubocop
for latest.

#### Why
Inline with test suites version or as close to
it as possible

### CODE REVIEW

**Review by kmahern — APPROVED** [review]
👍

**Comment by kmahern** [comment]
oh just seen code climate is failing  - do we need to filter out the existing rubocop violations in code climate too?

**Comment by jsugarman** [comment]
> oh just seen code climate is failing - do we need to filter out the existing rubocop violations in code climate too?

yeah, i am just seeing if i can fix them as they are good calls by codeclimate

**Comment by jsugarman** [comment]
@kmahern i have created separate PRs to group and handle the codeclimate warnings by type. I will ignore the wanrings in this PR to avoid scope creep. There is a [redundant Foreign key PR here](https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/pull/3614) which should be alright to merge but will sanity check it first if tests pass.

**Pull request merged**
