### PR TITLE
Optimize circleCI config

### PR DESCRIPTION
**Pull request by jsugarman**
#### What
Tidy circle CI 

#### Ticket
[CBO-649](https://dsdmoj.atlassian.net/browse/CBO-649)

#### Why
For clarity and to speed up test suite run

### CODE REVIEW

**Comment by jsugarman** [comment]
@colinbruce CodeClimate has gone down because of parallel runs not merging test results. could look at in this or get this in and work on separately - what u reckon?

**Comment by colinbruce** [comment]
I'd say merge and address later.  Maybe add an issue/jira ticket so we don't lose sight of it.  But as long as we're aware that the figures are not 100% representative I'd say go ahead.

p.s. It might also explain the 7% drop when we first moved to circle! ;)

**Comment by colinbruce** [comment]
Back up to 97% :boom:

**Review by colinbruce — APPROVED** [review]
LGTM :+1:

**Comment by jsugarman** [comment]
> LGTM 👍

cheers, just making a few tweaks then merge

**Pull request merged**
